version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ${APP_DIR}:/app/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
  console:
    hostname: docker-console
    container_name: docker-console
    restart: always
    build:
      context: .
      dockerfile: ./docker/console/Dockerfile
    volumes:
      - ${APP_DIR}:/app/
